# cmake/platforms/sdl3.cmake
#
# Build platform for the from-scratch SDL3 front end. Every puzzle is
# linked into a single combined binary (native) or, when configured
# under emcmake, a single Wasm image, driven by sdl3/sdlfe.c. Selected
# with -DPUZZLES_SDL3=ON.
#
# This is intentionally separate from the upstream emscripten platform
# (cmake/platforms/emscripten.cmake), and touches no puzzle sources, so
# the fork stays mergeable with upstream.

include(FetchContent)

# One combined target, built in build_platform_extras() like the macOS
# build. No per-puzzle binaries and no CLI/GUI helper tools.
set(build_individual_puzzles FALSE)
set(build_cli_programs FALSE)
set(build_gui_programs FALSE)
set(build_icons FALSE)
set(need_c_icons FALSE)

# We do not implement a native polygon fill; draw_polygon_fallback()
# (draw-poly.c) rasterises polygons through our draw_line().
add_compile_definitions(USE_DRAW_POLYGON_FALLBACK)

# Our front end is added directly to the combined target, not compiled
# into the core/common libraries (which must stay SDL-free).
set(platform_common_sources)
set(platform_gui_libs)
set(platform_libs)

if(CMAKE_C_COMPILER MATCHES "emcc" OR EMSCRIPTEN)
  set(PUZZLES_SDL3_WEB TRUE)
else()
  set(PUZZLES_SDL3_WEB FALSE)
endif()

# ---------------------------------------------------------------------
# Dependencies: SDL3, SDL_ttf and FreeType, built from source for both the
# native and web targets. Fetched as pinned HTTPS release tarballs verified
# by SHA256 -- reproducible and hermetic (no git clones or submodules).
# (SDL_ttf's own release tarball ships only dependency-download scripts, so
# we provide FreeType ourselves and point SDL_ttf at it.)
# ---------------------------------------------------------------------

# Force static, trimmed builds of the dependencies, and keep their own
# install rules out of our deploy directory (FreeType honours
# SKIP_INSTALL_ALL; SDL/SDL_ttf honour the *_INSTALL options below).
set(BUILD_SHARED_LIBS OFF)
set(SKIP_INSTALL_ALL ON CACHE BOOL "" FORCE)
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
set(SDL_TEST OFF CACHE BOOL "" FORCE)
set(SDL_TESTS OFF CACHE BOOL "" FORCE)
set(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)
set(SDL_INSTALL OFF CACHE BOOL "" FORCE)
# FreeType: minimal, no optional codecs (SDL_ttf only needs the rasteriser),
# so we don't pull in zlib/png/harfbuzz/brotli/bzip2.
set(FT_DISABLE_ZLIB ON CACHE BOOL "" FORCE)
set(FT_DISABLE_BZIP2 ON CACHE BOOL "" FORCE)
set(FT_DISABLE_PNG ON CACHE BOOL "" FORCE)
set(FT_DISABLE_HARFBUZZ ON CACHE BOOL "" FORCE)
set(FT_DISABLE_BROTLI ON CACHE BOOL "" FORCE)
# SDL_ttf: just the FreeType backend, using the FreeType we provide below.
set(SDLTTF_VENDORED OFF CACHE BOOL "" FORCE)
set(SDLTTF_SAMPLES OFF CACHE BOOL "" FORCE)
set(SDLTTF_HARFBUZZ OFF CACHE BOOL "" FORCE)
set(SDLTTF_PLUTOSVG OFF CACHE BOOL "" FORCE)
set(SDLTTF_INSTALL OFF CACHE BOOL "" FORCE)

FetchContent_Declare(freetype
  URL https://download.savannah.gnu.org/releases/freetype/freetype-2.13.3.tar.gz
  URL_HASH SHA256=5c3a8e78f7b24c20b25b54ee575d6daa40007a5f4eea2845861c3409b3021747
  OVERRIDE_FIND_PACKAGE)
FetchContent_Declare(SDL3
  URL https://github.com/libsdl-org/SDL/releases/download/release-3.2.30/SDL3-3.2.30.tar.gz
  URL_HASH SHA256=4c3b09330d866dc52eb65b66259a6684ad387252ca8c57901b3a2b534eb42e3d)
FetchContent_Declare(SDL3_ttf
  URL https://github.com/libsdl-org/SDL_ttf/releases/download/release-3.2.2/SDL3_ttf-3.2.2.tar.gz
  URL_HASH SHA256=63547d58d0185c833213885b635a2c0548201cc8f301e6587c0be1a67e1e045d)

# Build FreeType first and expose the target name SDL_ttf links against
# (find_package(Freetype) is satisfied by OVERRIDE_FIND_PACKAGE above).
FetchContent_MakeAvailable(freetype)
if(NOT TARGET Freetype::Freetype)
  add_library(Freetype::Freetype ALIAS freetype)
endif()
FetchContent_MakeAvailable(SDL3 SDL3_ttf)

# ---------------------------------------------------------------------
# Required platform hooks (see cmake/setup.cmake); mirrors osx.cmake.
# ---------------------------------------------------------------------
function(get_platform_puzzle_extra_source_files OUTVAR NAME AUXILIARY)
  set(${OUTVAR} PARENT_SCOPE)
endfunction()

function(set_platform_gui_target_properties TARGET)
endfunction()

function(set_platform_puzzle_target_properties NAME TARGET)
endfunction()

function(build_platform_extras)
  write_generated_games_header()

  # Generate a runtime metadata table (display name / description / objective)
  # from the CMake puzzle() metadata, so we don't have to touch any puzzle
  # source. Generated in the same sorted order as generated-games.h, so
  # puzzle_metadata[i] lines up with gamelist[i] in list.c.
  set(metadata_h ${generated_include_dir}/puzzle-metadata.h)
  file(WRITE ${metadata_h} "/* Generated by cmake/platforms/sdl3.cmake. */\n")
  file(APPEND ${metadata_h} "static const struct puzzle_metadata {\n")
  file(APPEND ${metadata_h}
    "    const char *name, *displayname, *description, *objective;\n")
  file(APPEND ${metadata_h} "} puzzle_metadata[] = {\n")
  set(sorted_names ${puzzle_names})
  list(SORT sorted_names)
  foreach(name ${sorted_names})
    file(APPEND ${metadata_h}
      "    {\"${name}\", \"${displayname_${name}}\", \"${description_${name}}\", \"${objective_${name}}\"},\n")
  endforeach()
  file(APPEND ${metadata_h} "};\n")
  file(APPEND ${metadata_h}
    "static const int n_puzzle_metadata =\n    sizeof puzzle_metadata / sizeof *puzzle_metadata;\n")

  add_executable(puzzles
    ${PUZZLES_ROOT_DIR}/sdl3/sdlfe.c
    ${PUZZLES_ROOT_DIR}/sdl3/storage.c
    list.c
    ${puzzle_sources})
  target_compile_definitions(puzzles PRIVATE COMBINED)
  if(PUZZLES_SDL3_WEB)
    # Assets/icons are preloaded into the virtual FS (see milestone 4).
    target_compile_definitions(puzzles PRIVATE
      PUZZLES_ASSET_DIR="/assets" PUZZLES_ICON_DIR="/icons")
  else()
    target_compile_definitions(puzzles PRIVATE
      PUZZLES_ASSET_DIR="${PUZZLES_ROOT_DIR}/sdl3/assets"
      PUZZLES_ICON_DIR="${PUZZLES_ROOT_DIR}/icons")
  endif()
  target_include_directories(puzzles PRIVATE
    ${generated_include_dir} ${PUZZLES_ROOT_DIR})
  target_link_libraries(puzzles
    common SDL3::SDL3 SDL3_ttf::SDL3_ttf ${platform_libs})

  if(PUZZLES_SDL3_WEB)
    set(CMAKE_EXECUTABLE_SUFFIX ".js")
    set_target_properties(puzzles PROPERTIES SUFFIX ".js" OUTPUT_NAME puzzles)

    # Preload fonts and the example states (icons/*.sav) into the virtual
    # FS, matching PUZZLES_ASSET_DIR=/assets and PUZZLES_ICON_DIR=/icons.
    set(preload
      "SHELL:--preload-file ${PUZZLES_ROOT_DIR}/sdl3/assets@/assets")
    file(GLOB sav_files ${PUZZLES_ROOT_DIR}/icons/*.sav)
    foreach(sav ${sav_files})
      get_filename_component(savname ${sav} NAME)
      list(APPEND preload "SHELL:--preload-file ${sav}@/icons/${savname}")
    endforeach()

    target_link_options(puzzles PRIVATE
      "SHELL:-s ALLOW_MEMORY_GROWTH=1"
      "SHELL:-s WASM=1"
      "SHELL:-s WASM_BIGINT"
      "SHELL:-s ENVIRONMENT=web"
      "SHELL:-s EXIT_RUNTIME=0"
      "SHELL:-s STACK_SIZE=1048576"
      ${preload})

    # Copy the PWA shell (index.html, manifest, service worker, icons)
    # next to the generated puzzles.js/.wasm/.data, so the build directory
    # is directly servable (e.g. with emrun) for local testing.
    file(COPY ${PUZZLES_ROOT_DIR}/web/ DESTINATION ${CMAKE_BINARY_DIR})

    # `cmake --install <build-dir> --prefix <dir>` assembles a flat,
    # deployable PWA directory (e.g. to publish to gh-pages): the Wasm
    # module, its preloaded data, and the shell + manifest + icons.
    install(FILES
      ${CMAKE_BINARY_DIR}/puzzles.js
      ${CMAKE_BINARY_DIR}/puzzles.wasm
      ${CMAKE_BINARY_DIR}/puzzles.data
      DESTINATION .)
    install(DIRECTORY ${PUZZLES_ROOT_DIR}/web/ DESTINATION .)
  endif()
endfunction()
